spring.application.name=backend

# MongoDB
spring.data.mongodb.uri=mongodb+srv://smartcampus:%23MarNif2003@cluster0.zxnz9x3.mongodb.net/smartcampus?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=smartcampus

# Server
server.port=8080

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile

# GitHub OAuth2
spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID:Ov23liGAG8uo4bx9pRQt}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET:9909599ca46e84eda06561f4cec53da96e325436}
spring.security.oauth2.client.registration.github.scope=user:email
spring.security.oauth2.client.registration.github.client-name=GitHub
spring.security.oauth2.client.provider.github.authorization-uri=https://github.com/login/oauth/authorize
spring.security.oauth2.client.provider.github.token-uri=https://github.com/login/oauth/access_token
spring.security.oauth2.client.provider.github.user-info-uri=https://api.github.com/user
spring.security.oauth2.client.provider.github.user-name-attribute=id

# JWT
app.jwt.secret=unisphere-super-secret-jwt-key-2026-group94-sliit
app.jwt.expiration=86400000

# Frontend URL
app.frontend.url=http://localhost:5173

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
app.mail.from=${MAIL_USERNAME}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
