spring.application.name=backend

# MongoDB
spring.data.mongodb.uri=mongodb+srv://smartcampus:#MarNif2003@cluster0.zxnz9x3.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=smartcampus

# Server
server.port=8080

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile

# JWT
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=86400000

# Frontend URL
app.frontend.url=http://localhost:5173