spring.application.name=backend

# MongoDB Configuration
spring.data.mongodb.uri=mongodb+srv://smartcampus:#MarNif2003@cluster0.zxnz9x3.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=smartcampus

# Server port
server.port=8080